### ISSUE TITLE
Warning stating signal type is not understood emitted even though signal type is in list

### ISSUE THREAD

**Issue by hakonanes** [hyperspy/hyperspy-extensions-list#21]
With HyperSpy v1.6.5 and kikuchipy v0.6.dev0, the warning

```python
2022-02-10 19:26:58,023 - hyperspy.io - WARNING - `signal_type='VirtualBSEImage'` not understood. See
`hs.print_known_signal_types()` for a list of installed signal types or
https://github.com/hyperspy/hyperspy-extensions-list for the list of all hyperspy extensions providing signals.
```

is emitted even though the signal type is in the list

```python
>>> hs.print_known_signal_types()
```

<div class="lm-Widget p-Widget jp-RenderedHTMLCommon jp-RenderedHTML jp-mod-trusted jp-OutputArea-output" data-mime-type="text/html">

signal_type | aliases | class name | package
-- | -- | -- | --
DielectricFunction | dielectric function | DielectricFunction | hyperspy
EBSD | electron_backscatter_diffraction | EBSD | kikuchipy
EBSDMasterPattern | ebsd_masterpattern, masterpattern | EBSDMasterPattern | kikuchipy
EDS_SEM |   | EDSSEMSpectrum | hyperspy
EDS_TEM |   | EDSTEMSpectrum | hyperspy
EELS | TEM EELS | EELSSpectrum | hyperspy
hologram |   | HologramImage | hyperspy
VirtualBSEImage | virtual_backscatter_electron_image | VirtualBSEImage | kikuchipy

</div>

I'll provide more information and investigate further in the near future.

**Comment by hakonanes** [comment]
The warning is only raised when the original signal the VirtualBSEImage is created from is a LazyEBSD instance. Seems like the VirtualBSEImage class is not available to lazy signals.

**Comment by ericpre** [comment]
```python
import numpy as np
import hyperspy.api as hs

s = hs.signals.BaseSignal(np.ones((10, 10)))
print(s)
s.set_signal_type('VirtualBSEImage')
print(s)
s_lazy = s.as_lazy()
print(s_lazy)
```

Give the following output:
```python
<BaseSignal, title: , dimensions: (|10, 10)>
<VirtualBSEImage, title: , dimensions: (|10, 10)>
<LazyVirtualBSEImage, title: , dimensions: (|10, 10)>
```

I seems that it has been fixed in https://github.com/pyxem/kikuchipy/pull/605.
