### ISSUE TITLE
Signal type package in README.md needs update

### ISSUE THREAD

**Issue by chenspc** [hyperspy/hyperspy-extensions-list#60]
Hello, 
I was helping a colleague debugging a hyperspy issue where he couldn't find the EDS signal type. The readme says it's built-in, but after some digging, it appears that `EDS_TEM` now belongs to exspy. After installing [exspy](https://github.com/hyperspy/exspy), I can see it with `print_known_signal_types()`. 

`DielectricFunction`, `EDS_SEM`, and `EELS` are also part of exspy. I suspect `hologram` is now part of holospy, but haven't tested myself. 

One small suggestion is to include the simple `conda install xxx` (and/or pip equivalent) instruction lines to [README.md](https://github.com/hyperspy/hyperspy-extensions-list/blob/main/README.md), as opposed to building an environment from a `.txt` file. Some new users may not be familiar with this approach. 

Thanks!

<img width="632" alt="Screenshot 2024-08-06 at 13 32 56" src="https://github.com/user-attachments/assets/80759d0a-bd74-4c0a-b551-029bce7cee60">

**Comment by ericpre** [comment]
Indeed this is out of date, because the workflow supposed to update it (https://github.com/hyperspy/hyperspy-extensions-list/actions/workflows/update_readme.yml) doesn't work - kikuchipy doesn't support hyperspy 2.0 which makes the script fail.

**Comment by jlaehne** [comment]
Resolved in #62
